# application.yaml
server:
  port: 8088
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/themapisto/spring-cloud-config-repository
testcode:
  testnumber: 1004
